### ISSUE TITLE
SolutionGenerator.MakeRelative is removing first char from folder name

### ISSUE THREAD

**Issue by norbertmanyi** [gerardog/VisualStudioImportExistingProjects#1]
on a project, in stead of
`Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Comparison.Models", "ComparisonTool\Comparison.Models\Comparison.Models.csproj", "{BF3D7AD1-8035-4C19-A803-66FD4587A399}"`
I get 
`Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Comparison.Models", "omparisonTool\Comparison.Models\Comparison.Models.csproj", "{BF3D7AD1-8035-4C19-A803-66FD4587A399}"`

It seems that this is from the +1 from the aforementioned method

Raising the issue because of the high degree of confusion (wanted to clarify why the +1 is there in stead of just doing a PR; perhaps there are some environment related issues I just haven't thought about)

Cheers,
Norbert

**Comment by gerardog** [comment]
Hi @norbertmanyi, sorry for reading this really late. I missed GitHub's notification.
The issue happens when you specify an output folder with a trailing backslash.
I fixed it in v1.1 release, commit #https://github.com/gerardog/VisualStudioImportExistingProjects/commit/db3563e383e306d230fdf8d595000fc4ee018627
Thanks for taking the time to report the issue.
